name: Release llmcat

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build binaries
        run: make all

      - name: Rename binaries for clarity
        run: |
          cd bin
          for os in darwin linux; do
            for arch in amd64 arm64; do
              mv ${os}/${arch}/llmcat llmcat-${os}-${arch}
            done
          done

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            bin/llmcat-darwin-amd64
            bin/llmcat-darwin-arm64
            bin/llmcat-linux-amd64
            bin/llmcat-linux-arm64
